//Login
export const FETCH_CURRENT_USER = 'fetch_current_user';
export const SIGNIN = 'signIn';
export const SIGNOUT = 'signOut';
export const LOGIN_ERROR = 'loginError';
export const PATIENT_ID = 'patientId';

//Usuario
export const MOSTRAR_CURRENT_USER = 'MOSTRAR_CURRENT_USER';
export const LOGIN_USER = 'LOGIN_USER';

//RRHH Empleado
export const MOSTRAR_EMPLEADOS = 'MOSTRAR_EMPLEADOS';
export const MOSTRAR_EMPLEADO = 'MOSTRAR_EMPLEADO';
export const AGREGAR_EMPLEADO = 'AGREGAR_EMPLEADO';
export const EDITAR_EMPLEADO = 'EDITAR_EMPLEADO';
export const BORRAR_EMPLEADO = 'BORRAR_EMPLEADO';
export const AGREGAR_DIRECCION_EMPLEADO = 'AGREGAR_DIRECCION_EMPLEADO';

//RRHH Roles
export const MOSTRAR_ROLES = 'MOSTRAR_ROLES';
export const MOSTRAR_ROL = 'MOSTRAR_ROL';
export const AGREGAR_ROL = 'AGREGAR_ROL';
export const EDITAR_ROL = 'EDITAR_ROL';
export const BORRAR_ROL = 'BORRAR_ROL';

//MODULO Producto
export const MOSTRAR_PRODUCTOS = 'MOSTRAR_PRODUCTOS';
export const MOSTRAR_PRODUCTO = 'MOSTRAR_PRODUCTO';
export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO';
export const EDITAR_PRODUCTO = 'EDITAR_PRODUCTO';
export const BORRAR_PRODUCTO = 'BORRAR_PRODUCTO';

//MODULO Categoria
export const MOSTRAR_CATEGORIAS = 'MOSTRAR_CATEGORIAS';
export const MOSTRAR_CATEGORIA = 'MOSTRAR_CATEGORIA';
export const AGREGAR_CATEGORIA = 'AGREGAR_CATEGORIA';
export const EDITAR_CATEGORIA = 'EDITAR_CATEGORIA';
export const BORRAR_CATEGORIA = 'BORRAR_CATEGORIA';

//RRHH Turnos
export const MOSTRAR_TURNOS = 'MOSTRAR_TURNOS';
export const MOSTRAR_TURNO = 'MOSTRAR_TURNO';
export const AGREGAR_TURNO = 'AGREGAR_TURNO';
export const EDITAR_TURNO = 'EDITAR_TURNO';
export const BORRAR_TURNO = 'BORRAR_TURNO';

//RRHH Asistencias
export const MOSTRAR_ASISTENCIAS = 'MOSTRAR_ASISTENCIAS';
export const MOSTRAR_ASISTENCIA = 'MOSTRAR_ASISTENCIA';
export const AGREGAR_ASISTENCIA = 'AGREGAR_ASISTENCIA';
export const EDITAR_ASISTENCIA = 'EDITAR_ASISTENCIA';
export const BORRAR_ASISTENCIA = 'BORRAR_ASISTENCIA';

//Gastos
export const MOSTRAR_GASTOS = 'MOSTRAR_GASTOS';
export const MOSTRAR_GASTO = 'MOSTRAR_GASTO';
export const AGREGAR_GASTO = 'AGREGAR_GASTO';
export const EDITAR_GASTO = 'EDITAR_GASTO';
export const BORRAR_GASTO = 'BORRAR_GASTO';

//Combos
export const MOSTRAR_COMBOS = 'MOSTRAR_COMBOOS';
export const MOSTRAR_COMBO = 'MOSTRAR_COMBO';
export const AGREGAR_COMBO = 'AGREGAR_COMBO';
export const EDITAR_COMBO = 'EDITAR_COMBO';
export const BORRAR_COMBO = 'BORRAR_COMBO';

//Pedidos
export const MOSTRAR_PEDIDOS = 'MOSTRAR_PEDIDOS';
export const MOSTRAR_PEDIDO = 'MOSTRAR_PEDIDO';
export const AGREGAR_PEDIDO = 'AGREGAR_PEDIDO';
export const EDITAR_PEDIDO = 'EDITAR_PEDIDO';
export const BORRAR_PEDIDO = 'BORRAR_PEDIDO';
export const ASIGNAR_DELIVERY = 'ASIGNAR_DELIVERY';

//Estados
export const MOSTRAR_ESTADOS = 'MOSTRAR_ESTADOS';
export const AGREGAR_ESTADO = 'AGREGAR_ESTADO';
export const EDITAR_ESTADO = 'EDITAR_ESTADO';
export const BORRAR_ESTADO = 'BORRAR_ESTADO';

//Clientes
export const MOSTRAR_CLIENTES = 'MOSTRAR_CLIENTES';
export const MOSTRAR_CLIENTE_TELEFONO = 'MOSTRAR_CLIENTE_TELEFONO';
export const AGREGAR_CLIENTE = 'AGREGAR_CLIENTE';
export const AGREGAR_DIRECCION_CLIENTE = 'AGREGAR_DIRECCION_CLIENTE';
export const EDITAR_CLIENTE = 'EDITAR_CLIENTE';
export const BORRAR_CLIENTE = 'BORRAR_CLIENTE';